"use client";
import Link from "next/link";
import Image from "next/image";
import { Menu, Search, ShoppingBag, UserRound, X } from "lucide-react";
import { AnimatePresence, motion } from "framer-motion";
import { useState } from "react";
import { useCart } from "@/components/providers/cart-provider";
import { useLanguage } from "@/components/providers/language-provider";
import { LanguageToggle } from "@/components/ui/language-toggle";
export function Navbar(){const [mobile,setMobile]=useState(false);const {count,setOpen}=useCart();const {t}=useLanguage();const nav=[{label:t("home"),href:"/"},{label:t("shop"),href:"/shop"},{label:t("story"),href:"/#about"},{label:t("why"),href:"/#why"},{label:t("contact"),href:"/#contact"}];return <header className="sticky top-0 z-40 border-b border-[#d8c79e]/80 bg-[#f8efd9]/90 shadow-sm backdrop-blur-xl"><div className="mx-auto flex h-[82px] max-w-7xl items-center justify-between px-5 lg:px-8"><Link href="/" aria-label="NIBBLY home" className="relative block h-[72px] w-[142px] overflow-hidden"><Image src="/nibbly-logo-crop.png" alt="NIBBLY Healthy Treats" fill sizes="142px" className="object-contain" priority/></Link><nav className="hidden items-center gap-7 lg:flex">{nav.map(item=><Link key={item.href} href={item.href} className="text-sm font-medium text-[#354B2D]/80 transition hover:text-[#c77725]">{item.label}</Link>)}</nav><div className="flex items-center gap-1.5 text-[#354B2D]"><LanguageToggle/><button aria-label="Search" className="hidden p-2 hover:text-[#c77725] sm:block"><Search size={20}/></button><button aria-label="Account" className="hidden p-2 hover:text-[#c77725] sm:block"><UserRound size={20}/></button><button aria-label="Open cart" onClick={()=>setOpen(true)} className="relative p-2 hover:text-[#c77725]"><ShoppingBag size={21}/>{count>0&&<span className="absolute right-0 top-0 grid size-4 place-items-center rounded-full bg-[#c65752] text-[9px] font-bold text-white">{count}</span>}</button><button aria-label="Open menu" onClick={()=>setMobile(!mobile)} className="p-2 lg:hidden">{mobile?<X/>:<Menu/>}</button></div></div><AnimatePresence>{mobile&&<motion.nav initial={{height:0,opacity:0}} animate={{height:"auto",opacity:1}} exit={{height:0,opacity:0}} className="overflow-hidden border-t border-[#d8c79e] bg-[#f5ead2] px-6 lg:hidden">{nav.map(item=><Link onClick={()=>setMobile(false)} key={item.href} href={item.href} className="block py-3 text-sm font-medium text-[#354B2D]">{item.label}</Link>)}</motion.nav>}</AnimatePresence></header>}
