"use client";
import Link from "next/link";
import { Heart, ShoppingBag, Star } from "lucide-react";
import { motion } from "framer-motion";
import { useState } from "react";
import type { Product } from "@/data/products";
import { ProductArt } from "@/components/ui/product-art";
import { useCart } from "@/components/providers/cart-provider";
import { useLanguage } from "@/components/providers/language-provider";
export function ProductCard({ product }: { product: Product }) {
 const { add } = useCart(); const {lang,t}=useLanguage(); const [liked,setLiked]=useState(false); const color = product.category === "Granola" ? "bg-[#FFF2B4]" : product.category === "Nut Mix" || product.category === "Trail Mix" ? "bg-[#DFF3C1]" : product.category === "Energy Bites" || product.category === "Protein Snacks" ? "bg-[#DDF3FF]" : product.category === "Healthy Cookies" || product.category === "Fruit Snacks" ? "bg-[#FFE0E8]" : "bg-[#F0E5FF]"; const badge = product.badge === "BEST SELLER" ? "bg-[#FF718D]" : product.badge === "VEGAN" ? "bg-[#62BFA1]" : product.badge === "HEALTHY PICK" ? "bg-[#6EC8FF]" : product.badge === "LIMITED" ? "bg-[#A678FF]" : product.badge === "POPULAR" ? "bg-[#FF9F43]" : "bg-[#8BC34A]"; const categories:Record<string,string>={Granola:"กราโนล่า","Nut Mix":"ถั่วรวม","Energy Bites":"เอเนอร์จี้ไบต์","Dried Fruits":"ผลไม้อบแห้ง","Fruit Snacks":"ฟรุตสแน็ก","Oat Snacks":"โอ๊ตสแน็ก","Healthy Cookies":"คุกกี้เพื่อสุขภาพ","Protein Snacks":"โปรตีนสแน็ก","Trail Mix":"เทรลมิกซ์"};
 return <motion.article initial={{ opacity: 0, y: 16 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} whileHover={{ y: -8, rotate: -.3 }} className={`group relative overflow-hidden rounded-[28px] border border-white/70 bg-[#FFF8E8] p-3 shadow-[0_12px_30px_rgba(87,71,91,.12)] ${color}`}>
   <Link href={`/shop/${product.slug}`} className="block"><div className="relative overflow-hidden rounded-[22px]"><ProductArt variant={product.art} image={product.image} alt={product.name} className="aspect-[1.05] transition-transform duration-500 group-hover:scale-105" />{product.badge && <span className={`absolute left-3 top-3 rounded-full ${badge} px-2.5 py-1 text-[9px] font-extrabold tracking-wider text-white shadow-sm`}>{product.badge}</span>}<button onClick={(e)=>{e.preventDefault();setLiked(!liked)}} aria-label={`Favorite ${product.name}`} className={`absolute right-3 top-3 grid size-8 place-items-center rounded-full bg-white/90 transition hover:scale-110 ${liked?"text-[#FF718D]":"text-[#8B5E3C]"}`}><Heart size={15} fill={liked?"currentColor":"none"}/></button></div></Link>
   <div className="px-1 pb-1 pt-4"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#8B5E3C]/60">{lang==="th"?categories[product.category]:product.category}</p><div className="mt-1 flex items-center gap-1 text-xs text-[#FF9F43]"><Star size={13} fill="currentColor"/><span className="font-semibold">{product.rating}</span><span className="text-stone-400">({product.reviews} {t("reviews")})</span></div><Link href={`/shop/${product.slug}`}><h3 className="mt-2 font-display text-xl leading-tight text-[#354B2D]">{product.name}</h3></Link><p className="mt-1 h-9 text-xs leading-relaxed text-stone-500">{product.description}</p><div className="mt-4 flex items-center justify-between gap-2"><span className="font-display text-xl text-[#8B5E3C]">฿{product.price}</span><button onClick={() => add(product)} className="inline-flex items-center gap-1 rounded-full bg-[#354B2D] px-3 py-2 text-xs font-bold text-white transition hover:scale-105 hover:bg-[#FF718D]"><ShoppingBag size={14}/> {t("add")}</button></div></div>
 </motion.article>;
}
