"use client";
import { Search, SlidersHorizontal } from "lucide-react";
import { useMemo, useState } from "react";
import { products } from "@/data/products";
import { ProductCard } from "./product-card";
import { useLanguage } from "@/components/providers/language-provider";
const categories=["All","Granola","Nut Mix","Energy Bites","Dried Fruits","Fruit Snacks","Oat Snacks","Healthy Cookies","Protein Snacks","Trail Mix"];
const categoryTh:Record<string,string>={All:"ทั้งหมด",Granola:"กราโนล่า","Nut Mix":"ถั่วรวม","Energy Bites":"เอเนอร์จี้ไบต์","Dried Fruits":"ผลไม้อบแห้ง","Fruit Snacks":"ฟรุตสแน็ก","Oat Snacks":"โอ๊ตสแน็ก","Healthy Cookies":"คุกกี้เพื่อสุขภาพ","Protein Snacks":"โปรตีนสแน็ก","Trail Mix":"เทรลมิกซ์"};
export function ShopBrowser(){const {lang,t}=useLanguage();const [category,setCategory]=useState("All"),[query,setQuery]=useState(""),[sort,setSort]=useState("Recommended"),[shown,setShown]=useState(8);const filtered=useMemo(()=>products.filter(p=>(category==="All"||p.category===category)&&p.name.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==="low"?a.price-b.price:sort==="high"?b.price-a.price:sort==="rated"?b.rating-a.rating:0),[category,query,sort]);const options=[{v:"Recommended",l:t("recommended")},{v:"low",l:t("low")},{v:"high",l:t("high")},{v:"rated",l:t("rated")}];return <><div className="mt-8 flex flex-col gap-4 rounded-[24px] border border-[#e6d7b8] bg-[#f7edd9] p-4 lg:flex-row lg:items-center lg:justify-between"><label className="flex flex-1 items-center gap-2 rounded-full bg-[#f1e5cd] px-4 py-3 text-stone-400"><Search size={18}/><input value={query} onChange={e=>{setQuery(e.target.value);setShown(8)}} placeholder={t("search")} className="w-full bg-transparent text-sm text-[#354B2D] outline-none placeholder:text-stone-400"/></label><div className="flex items-center gap-2"><SlidersHorizontal size={17} className="text-[#618a45]"/><select value={sort} onChange={e=>setSort(e.target.value)} aria-label="Sort products" className="bg-transparent text-sm font-medium text-[#354B2D] outline-none">{options.map(o=><option key={o.v} value={o.v}>{o.l}</option>)}</select></div></div><div className="mt-5 flex gap-2 overflow-x-auto pb-2">{categories.map(c=><button key={c} onClick={()=>{setCategory(c);setShown(8)}} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm font-semibold transition ${category===c?"bg-[#354B2D] text-[#fff8e8]":"border border-[#d9c7a4] bg-[#f8eed9] text-[#354B2D] hover:bg-[#e9d7af]"}`}>{lang==="th"?categoryTh[c]:c}</button>)}</div>{filtered.length?<><p className="mt-7 text-sm text-stone-500"><b className="text-[#354B2D]">{filtered.length}</b> {t("results")}</p><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{filtered.slice(0,shown).map(p=><ProductCard key={p.id} product={p}/>)}</div>{shown<filtered.length&&<div className="mt-10 text-center"><button onClick={()=>setShown(s=>s+4)} className="rounded-full border border-[#354B2D] px-6 py-3 text-sm font-bold text-[#354B2D] transition hover:bg-[#354B2D] hover:text-[#fff8e8]">{t("load")}</button></div>}</>:<div className="mt-9 rounded-[28px] border border-dashed border-[#d8c594] bg-[#f7edd9] py-16 text-center"><span className="text-4xl">🍃</span><h2 className="mt-3 font-display text-3xl text-[#354B2D]">{t("empty")}</h2><p className="mt-2 text-sm text-stone-500">{t("emptySub")}</p><button onClick={()=>{setCategory("All");setQuery("")}} className="mt-5 rounded-full bg-[#354B2D] px-5 py-2.5 text-sm font-bold text-[#fff8e8]">{t("seeAll")}</button></div>}</>}
