"use client";
import { createContext, useContext, useEffect, useMemo, useState } from "react";
export type Language = "th" | "en";
const copy = {
  en: { home:"Home",shop:"Shop",story:"Our Story",why:"Why NIBBLY",contact:"Contact",search:"Search a snack...",recommended:"Recommended",low:"Price: low to high",high:"Price: high to low",rated:"Best rated",add:"Add",added:"Added to your snack box! 🍓",cart:"Your happy bag",browse:"Browse snacks",viewCart:"View Cart",checkout:"Checkout securely",shopAll:"Shop all snacks.",pantry:"OUR COLORFUL PANTRY",shopSub:"Find your happy flavour—from crispy granola to chewy little energy bites.",results:"snacks to discover",load:"Load more goodness",empty:"No snacks found",emptySub:"Try a different word, or explore all our happy treats.",seeAll:"See all snacks",category:"Category",reviews:"reviews",addBag:"Add to happy bag",buy:"Buy now",free:"Free shipping",freeSub:"On orders above ฿500",guarantee:"Happy guarantee",guaranteeSub:"Made with ingredients you’ll love",description:"Description",ingredients:"Ingredients",nutrition:"Nutrition",review:"Reviews",allergens:"Allergens",perfect:"PERFECT FOR",storage:"Storage: keep sealed in a cool, dry place. Best enjoyed whenever you need a little happy.",related:"You may also like",explore:"KEEP EXPLORING" },
  th: { home:"หน้าแรก",shop:"ร้านขนม",story:"เรื่องของเรา",why:"ทำไมต้อง NIBBLY",contact:"ติดต่อเรา",search:"ค้นหาขนมที่อยากกิน...",recommended:"แนะนำ",low:"ราคา: น้อยไปมาก",high:"ราคา: มากไปน้อย",rated:"คะแนนสูงสุด",add:"เพิ่ม",added:"ใส่ลงกล่องขนมแล้ว! 🍓",cart:"ถุงขนมของคุณ",browse:"เลือกขนม",viewCart:"ดูตะกร้า",checkout:"ไปชำระเงิน",shopAll:"เลือกขนมทั้งหมด",pantry:"ตู้ขนมหลากสีของเรา",shopSub:"หาเมนูที่ใช่ ตั้งแต่กราโนล่ากรอบ ๆ ไปจนถึงไบต์คำเล็กเคี้ยวเพลิน",results:"รายการให้เลือก",load:"ดูเพิ่ม",empty:"ยังไม่เจอขนมที่ค้นหา",emptySub:"ลองเปลี่ยนคำค้น หรือดูขนมทั้งหมดของเรา",seeAll:"ดูขนมทั้งหมด",category:"หมวด",reviews:"รีวิว",addBag:"ใส่ลงถุงขนม",buy:"ซื้อเลย",free:"ส่งฟรี",freeSub:"เมื่อสั่งครบ ฿500",guarantee:"รับประกันความอร่อย",guaranteeSub:"คัดสรรวัตถุดิบที่คุณสบายใจ",description:"รายละเอียด",ingredients:"ส่วนประกอบ",nutrition:"โภชนาการ",review:"รีวิว",allergens:"สารก่อภูมิแพ้",perfect:"เหมาะกับ",storage:"เก็บในที่แห้งและเย็น ปิดซองให้สนิท เพื่อความอร่อยในทุกคำ",related:"ขนมที่คุณน่าจะชอบ",explore:"ลองดูต่ออีกนิด" }
} as const;
type CopyKey = keyof typeof copy.en;
const LanguageContext = createContext<{lang:Language;setLang:(l:Language)=>void;t:(key:CopyKey)=>string}>({lang:"th",setLang:()=>{},t:(key)=>copy.th[key]});
export function LanguageProvider({children}:{children:React.ReactNode}) { const [lang,setLang]=useState<Language>("th"); useEffect(()=>{const saved=localStorage.getItem("nibbly-language");if(saved==="en"||saved==="th")setLang(saved)},[]); const value=useMemo(()=>({lang,setLang:(next:Language)=>{setLang(next);localStorage.setItem("nibbly-language",next)},t:(key:CopyKey)=>copy[lang][key]}),[lang]); return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider> }
export const useLanguage=()=>useContext(LanguageContext);
